name: Publish Images Using Commit Hash

on:
  push:
    branches:
      - main

jobs:
  publish-binary-artifacts:
    name: Publish Image
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Push the binary artifacts image on the docker registry
      uses: Ferlab-Ste-Justine/action-push-image@master
      with:
        username: ${{ secrets.FERLAB_DOCKER_HUB_USER }}
        password: ${{ secrets.FERLAB_DOCKER_HUB_TOKEN }}
        image: ferlabcrsj/binary-artifacts
        tag_source: sha
        location: binary-artifacts
        dockerfile: binary-artifacts/Dockerfile