name: Publish Images Using Commit Hash

on:
  push:
    branches:
      - main

jobs:
  publish-binary-artifacts:
    name: Publish Image
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Push the binary artifacts image on the docker registry
      uses: Ferlab-Ste-Justine/action-push-image@master
      with:
        username: chusj
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        image: chusj/binary-artifacts
        tag_source: sha
        location: binary-artifacts
        dockerfile: binary-artifacts/Dockerfile